# Generated by Django 2.2.12 on 2021-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'VisualisationData',
            },
        ),
    ]
